### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by gbtami** [nathan-hoad/gbulb#26] opened 2017-05-26 20:43 UTC
Today I'v seen this in PyChess console wile playin a human-human test game:
```
Exception ignored in: <function wait_signal.__init__.<locals>.<lambda> at 0x7f1f6df38ea0>
Traceback (most recent call last):
  File "/home/tamas/pychess/lib/pychess/external/gbulb/utils.py", line 46, in <lambda>
    self._obj = weakref.ref(obj, lambda s: self.cancel())
  File "/home/tamas/pychess/lib/pychess/external/gbulb/utils.py", line 58, in cancel
    super().cancel()
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
    self._schedule_callbacks()
  File "/usr/lib/python3.5/asyncio/futures.py", line 236, in _schedule_callbacks
    callbacks = self._callbacks[:]
AttributeError: 'wait_signal' object has no attribute '_callbacks'
```

I use gbulb latest git version in PyChess. Unfortunately I can't reproduce this again.

**Comment by nathan-hoad** [comment] 2017-10-28 00:49
Given this can't be reproduced and hasn't been since for a while, I'm closing this.

**Closed by nathan-hoad** 2017-10-28 00:49 UTC
